# bouncy ball parameters

# impedance control parameters
translational_stiffness: 500 #500
rotational_stiffness: 900   #900
translational_damping_ratio: 20 # 1
rotational_damping: 50 # temporary increase for safety # 10 to 50   #50

translational_integral_gain: 0
rotational_integral_gain: 0
integrator_clamp: [30, 30, 30, 30, 8, 8, 8]

stiffness_null: 4 #4
damping_null: 4 #4
q_null_desired: [0, 0.361, 0, -2.223, 0, 2.584, 0]
moving_offset: 0 #0.0005
pushing_offset: 0 #-0.001

# c3 parameters
mu: 1                  # changes need to be consistent with urdf
Q_default: 0
Q_finger: 50   # 500      # finger xyz cost           # APPROX： 500
Q_ball_x: 500000 # 10000                              # APPROX： 1000000
Q_ball_y: 500000 # 10000                              # APPROX： 1000000
Q_ball_z: 0 # 10000                              # APPROX： 1000000
Q_finger_vel: 10        # 10 translational velocity cost
Q_ball_vel: 0.1         # 0.1 angular & translational velocity cost
Qnew_finger: 500    # 1000000  Qnew costs             # APPROX： 500
Qnew_ball_x: 1                                         # APPROX： 1
Qnew_ball_y: 1                                         # APPROX： 1
R: 0.01                 # torque cost in xyz
G: 0.01                 # 0.01
U_default: 1
U_pos_vel: 10           # first 19 diag elements of U
U_u: 1                # last 3 diag elements of U
q_init_finger: [0, 0, 0.085] #[0, 0, 0.0775] CHANGED THIS
q_init_ball_c3: [1, 0, 0, 0, 0.05, 0.05, 0.03] # last 3 elements don't matter
dt: 0.015 # 0.03
velocity_limit: 1
orientation_degrees: 20
axis_option: 1

# initialization/simulation parameters
q_init_franka: [0, 0.275, 0, -2.222, 0, 2.497, 0]
q_init_ball: [1, 0, 0, 0] # xyz computed according to x_c, y_c, traj_radius, phase, and ball_radius
initial_start: [0.55, 0, 0.12]
initial_finish: [0, 0, 0.09]  # [0, 0, 0.07]  # xy computed according to x_c, y_c, traj_radius, and phase
stabilize_time1: 0.5 #0.5
move_time: 0.75 #0.75
stabilize_time2: 0.75 #0.75
sim_dt: 0.0001
realtime_rate: 0.5

# trajectory parameters
traj_radius: 0.1 # 0.1
phase: 180
x_c: 0.55
y_c: 0
degree_increment: 20
time_increment: 1
hold_order: 0 # 0 for zero order hold, 1 for first order hold

# if enable_adaptive_path is set to 1, the trajectory above is not used
lead_angle: -15 # angle in degrees
enable_adaptive_path: 1 # 0 to use regular path, 1 to use path that adjusts to ball in real time

# geometry parameters
ball_radius: 0.0315           # changes need to be consistent with sphere urdf, geometry mesh, AND vision
ball_model_radius: 0.0315     # changes need to be consistent with sphere_model urdf (collision part), geometry mesh, AND vision
finger_radius: 0.0195         # changes need to be consistent with franka_box and model urdfs
EE_offset: [0, 0, 0.0153]     # changes need to be consistent with franka_box urdf
table_offset: -0.0038 #-0.0245      # chances need to be consistent with franka_box, model urdf, AND vision
model_table_offset: -0.0038 #-0.0245 # changes need to be consistent with model urdf

# Misc
contact_threshold: 0.01
enable_heuristic: 0
enable_contact: 1
ball_stddev: 0.00 # standard deviation of 0-mean noise on ball state estimation

# gaiting parameters
roll_phase: 1.5  #2.5                           # APPROX： 1.5 (realtime rate 1)
return_phase: 0.5 #0.75                         # APPROX： 0.8 (realtime rate 1)
gait_parameters: [0.025, 0.0921, 0.0891, 0.0701] # [0.02, 0.0951, 0.0911, 0.0691] try playing with first param here
# [0.025, 0.0921, 0.0891, 0.0701] work good for right and large model
# gait parameters represent height above the table

# filters
dt_filter_length: 10
alpha_p: 0.2
alpha_v: 1

# filter_new (FIR low pass), cutoff_freq is normalized, normalized = cutoff * 2 / sample frequency
position_degree: 12
position_cutoff_freq: 0.1
position_window: hamming

velocity_degree: 10
velocity_cutoff_freq: 0.1
velocity_window: hamming

# this should be automatic generated by running python scripts
position_FIR_para: [0.006790694131532139, 0.01516872887183891, 0.03947090963953053,
  0.07798287760550007, 0.12118490366168656, 0.15528387720634734, 0.1682360177671288,
  0.15528387720634734, 0.12118490366168658, 0.07798287760550007, 0.03947090963953059,
  0.015168728871838915, 0.006790694131532139]
velocity_FIR_para: [0.00996728268387249, 0.024861659826968308, 0.06683668904188193,
  0.12488893910660492, 0.1755918604159645, 0.19570713784941593, 0.1755918604159645,
  0.12488893910660492, 0.06683668904188193, 0.024861659826968308, 0.00996728268387249]

